{
  "formatVersion": "1.1",
  "component": {
    "group": "com.oracle.coherence",
    "module": "coherence-gradle-plugin",
    "version": "15.1.1-0-0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "coherence-gradle-plugin-15.1.1-0-0-SNAPSHOT.jar",
          "url": "coherence-gradle-plugin-15.1.1-0-0-SNAPSHOT.jar",
          "size": 18636,
          "sha512": "924546654807cfdec571333e177ee1f9579aafd3ed968dc84dfd4e6448154e66e34dc03dc214524a80693b4b22b0d6fd9dabc6f15715be6154fa6eb935468b68",
          "sha256": "281d9e6d9980cc62de14ef9c89cb5caa93d1ca1e4a249b2c78cda35f1829c78f",
          "sha1": "aef2b908c2e0da0ba4ca309cfaab3348af7e9741",
          "md5": "d3bf6d1ea7802bb3e5d5c966921a9a48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.oracle.coherence",
          "module": "coherence",
          "version": {
            "requires": "15.1.1-0-0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "coherence-gradle-plugin-15.1.1-0-0-SNAPSHOT.jar",
          "url": "coherence-gradle-plugin-15.1.1-0-0-SNAPSHOT.jar",
          "size": 18636,
          "sha512": "924546654807cfdec571333e177ee1f9579aafd3ed968dc84dfd4e6448154e66e34dc03dc214524a80693b4b22b0d6fd9dabc6f15715be6154fa6eb935468b68",
          "sha256": "281d9e6d9980cc62de14ef9c89cb5caa93d1ca1e4a249b2c78cda35f1829c78f",
          "sha1": "aef2b908c2e0da0ba4ca309cfaab3348af7e9741",
          "md5": "d3bf6d1ea7802bb3e5d5c966921a9a48"
        }
      ]
    }
  ]
}
