{
  "formatVersion": "1.1",
  "component": {
    "group": "com.oracle.coherence",
    "module": "coherence-gradle-plugin",
    "version": "15.1.1-0-0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "coherence-gradle-plugin-15.1.1-0-0-SNAPSHOT.jar",
          "url": "coherence-gradle-plugin-15.1.1-0-0-SNAPSHOT.jar",
          "size": 18730,
          "sha512": "730ea44daf661065f40fc25ef1fe88b5174fb83d219e47e793be318ff3e1fda25b6510b752a2738924e6223d7867dbf82899797a0a2fa23b61f4a6d2e097738d",
          "sha256": "5ba67687552f32c643f7b5d248dc35cfde1f406954c6043f9054230d05b7772e",
          "sha1": "71ea0e322795bb0da3585ef39c8d0e807494e740",
          "md5": "8a32761f5a46d717d814661022acda8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.oracle.coherence",
          "module": "coherence",
          "version": {
            "requires": "15.1.1-0-0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "coherence-gradle-plugin-15.1.1-0-0-SNAPSHOT.jar",
          "url": "coherence-gradle-plugin-15.1.1-0-0-SNAPSHOT.jar",
          "size": 18730,
          "sha512": "730ea44daf661065f40fc25ef1fe88b5174fb83d219e47e793be318ff3e1fda25b6510b752a2738924e6223d7867dbf82899797a0a2fa23b61f4a6d2e097738d",
          "sha256": "5ba67687552f32c643f7b5d248dc35cfde1f406954c6043f9054230d05b7772e",
          "sha1": "71ea0e322795bb0da3585ef39c8d0e807494e740",
          "md5": "8a32761f5a46d717d814661022acda8d"
        }
      ]
    }
  ]
}
